name: Pylint

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: abatilo/actions-poetry@v2.0.0
    - name: Install dependencies
      run: poetry install
    - name: Analysing the code with pylint
      run: |
        poetry run pylint src/ tests/
